# Generated by Django 2.2.3 on 2019-12-21 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20191221_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cloth',
            field=models.CharField(blank=True, choices=[('leather', 'Leather'), ('cotton', 'Cotton')], max_length=10, null=True),
        ),
    ]
