# Generated by Django 2.2.3 on 2020-02-09 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20191221_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, choices=[('white', '#FEFEFE'), ('green', '#3FA434'), ('black', '#010500'), ('grey', '#9C9E9C'), ('other', '#D0D1D0')], max_length=10, null=True),
        ),
    ]
