# Generated by Django 2.2.3 on 2020-02-18 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20200218_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sell_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(default='Świetny produkt. Polecam !!!'),
        ),
    ]
