# Generated by Django 2.2.3 on 2020-05-14 19:29

from django.db import migrations, models
import product.utils


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20200512_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='card_image',
            field=models.ImageField(default='default.jpg', upload_to=product.utils.upload_image_path),
        ),
    ]
