# Generated by Django 2.2.3 on 2020-05-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_product_card_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='content',
            field=models.TextField(default='Prezentowany model z kolekcji vero Amareno to funkcjonalny narożnik, który  pozwoli nam cieszyć się każdą chwilą. Niełatwo jest być bohaterem dnia codziennego, ale gdy w salonie gości narożnik wielofunkcyjny, sukces w tej dziedzinie jest już tylko kwestią czasu. Wizyta rodziny, zmęczenie po pracy, czy zwyczajna ochota na zmianę miejsca spania, to okoliczności, które powodują, że w salonie nie może zabraknąć narożnika z funkcją spania (sposób rozkładania - stelaż "włoski"). Wygodny narożnik może być idealnym zamiennikiem klasycznego łóżka zarówno w sytuacjach awaryjnych, jak i na co dzień.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=4851, max_digits=9),
        ),
    ]
