# Generated by Django 2.2.3 on 2020-02-09 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191208_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='facebook_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.CharField(default='default.jpg', max_length=300),
        ),
    ]
