# Generated by Django 2.2.3 on 2020-05-12 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200218_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(default='dafault.jpg', upload_to='profile_images/'),
        ),
    ]
