# Generated by Django 2.2.3 on 2020-05-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200514_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(default='wiedzmin.jpeg', upload_to=''),
        ),
    ]
