# Generated by Django 2.2.3 on 2019-12-20 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20191220_0503'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['items']},
        ),
    ]
